"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-x@b^(7!!cu52#!+1l)m1@rf3hkc$*#8f-039x&d(tyhs$niav)')

# Clave simétrica (Fernet) para cifrar `ConfiguracionPAC.api_key_cifrada`
# (feature 016 · Configuración Fiscal). Mismo criterio que SECRET_KEY: valor
# de desarrollo aquí como fallback, se espera que producción la sobreescriba
# vía variable de entorno (`.env`, ya excluido del repositorio).
FISCAL_ENCRYPTION_KEY = os.environ.get('FISCAL_ENCRYPTION_KEY', '8Sfb_pSwAbrOdD5b0P7O15cl7cSLCb1i4TR4y2A-n6c=')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'apps.usuarios',
    'apps.sucursales',
    'apps.catalogo',
    'apps.inventario',
    'apps.personas',
    'apps.terceros',
    'apps.rrhh',
    'apps.compras',
    'apps.caja',
    'apps.ventas',
    'apps.produccion',
    'apps.reportes',
    'apps.configuracion_fiscal',
    'apps.facturacion',
    'apps.contabilidad',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME', 'synapse_erp'),
        'USER': os.environ.get('DB_USER', 'synapse'),
        'PASSWORD': os.environ.get('DB_PASSWORD', ''),
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PORT': os.environ.get('DB_PORT', '5434'),
    }
}


AUTH_USER_MODEL = 'usuarios.Usuario'


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_THROTTLE_RATES': {
        # Límite de intentos de login por IP, para mitigar fuerza bruta.
        'login': '5/min',
        # Ambos limitados por correo destino (ver ThrottlePorCorreoDestino),
        # no por IP: evita que se sature la bandeja de un usuario específico.
        'recuperar_password': '3/hour',
        'verificar_codigo': '5/min',
    },
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
}

CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get('CORS_ALLOWED_ORIGINS', 'http://localhost:5173').split(',')
    if origin.strip()
]


# Correo saliente (feature 004 · Recuperar contraseña)
# El backend a usar depende de si hay credenciales SMTP configuradas
# (EMAIL_HOST en .env), no de DEBUG — así se puede probar el envío real
# también en desarrollo sin forzar DEBUG=False (que activa otro
# comportamiento no relacionado, como páginas de error genéricas). Sin
# EMAIL_HOST configurado, los correos se imprimen en la consola del
# runserver en vez de enviarse de verdad, para no requerir credenciales SMTP
# reales solo para levantar el entorno local.
EMAIL_BACKEND = os.environ.get(
    'EMAIL_BACKEND',
    'django.core.mail.backends.smtp.EmailBackend' if os.environ.get('EMAIL_HOST') else 'django.core.mail.backends.console.EmailBackend',
)
EMAIL_HOST = os.environ.get('EMAIL_HOST', '')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'no-reply@synapse-erp.local')


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

# 'America/Mexico_City', no 'UTC' (default sin tocar del scaffold original):
# 014 · Dashboard calcula límites de "día/semana/mes" con
# `timezone.localtime()` — con TIME_ZONE=UTC, la medianoche usada para esos
# cortes no coincidía con la medianoche real del negocio (México), corriendo
# los datos de un bucket al día equivocado. Los timestamps siguen
# guardándose en UTC en la base de datos (USE_TZ=True no cambia); esto solo
# afecta a qué "hoy" local se convierten al mostrarlos/agruparlos.
TIME_ZONE = 'America/Mexico_City'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'


# Archivos generados por 017 · Facturación (XML/PDF de cada CFDI timbrado).
# Sin URL pública servida por Django (`MEDIA_URL` no se conecta en
# `config/urls.py`) — la descarga siempre pasa por las acciones
# autenticadas de `FacturaViewSet`, nunca por un archivo estático abierto.
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Fotografías de empleado (008 · RRHH) — storage y URL propios, separados de
# `MEDIA_ROOT`/`MEDIA_URL`, que a propósito no se conectan en `config/urls.py`
# (ver nota arriba). Las fotos son menos sensibles que un CFDI y sí se sirven
# por una URL estática simple bajo `DEBUG`, pero desde su propia carpeta para
# no arrastrar esa exposición a los archivos de Facturación si en algún
# momento `MEDIA_URL` llegara a conectarse.
EMPLEADOS_FOTOS_URL = 'fotos-empleados/'
EMPLEADOS_FOTOS_ROOT = BASE_DIR / 'media_rrhh' / 'fotos_empleados'
