# Generated by Django 6.0.7 on 2026-08-03 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sucursal', models.CharField(max_length=150)),
                ('ubicacion_sucursal', models.CharField(blank=True, max_length=255)),
                ('telefono_sucursal', models.CharField(blank=True, max_length=30)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
