# Generated by Django 6.0.7 on 2026-09-12 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_alter_venta_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='gasto_envio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
