# Generated by Django 6.0.7 on 2026-08-30 03:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ventas', '0002_alter_venta_fecha'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio_fiscal', models.CharField(blank=True, max_length=36, verbose_name='UUID fiscal')),
                ('serie', models.CharField(blank=True, max_length=10)),
                ('folio_interno', models.PositiveIntegerField(blank=True, null=True)),
                ('uso_cfdi', models.CharField(max_length=4)),
                ('forma_pago', models.CharField(max_length=2)),
                ('metodo_pago', models.CharField(choices=[('PUE', 'Pago en una sola exhibición'), ('PPD', 'Pago en parcialidades o diferido')], max_length=3)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('timbrada', 'Timbrada'), ('pendiente_cancelacion', 'Pendiente de cancelación'), ('cancelada', 'Cancelada'), ('error', 'Error')], default='pendiente', max_length=25)),
                ('mensaje_error', models.TextField(blank=True)),
                ('xml_path', models.CharField(blank=True, max_length=255)),
                ('pdf_path', models.CharField(blank=True, max_length=255)),
                ('motivo_cancelacion', models.CharField(blank=True, choices=[('01', '01 — Comprobante emitido con errores con relación'), ('02', '02 — Comprobante emitido con errores sin relación'), ('03', '03 — No se llevó a cabo la operación'), ('04', '04 — Operación nominativa relacionada en una factura global')], max_length=2)),
                ('fecha_solicitud_cancelacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('fecha_timbrado', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to=settings.AUTH_USER_MODEL)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='ventas.venta')),
            ],
            options={
                'verbose_name_plural': 'facturas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ComplementoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_pago', models.DateField()),
                ('folio_fiscal_rep', models.CharField(blank=True, max_length=36, verbose_name='UUID fiscal del REP')),
                ('estado', models.CharField(choices=[('timbrada', 'Timbrado'), ('error', 'Error')], default='timbrada', max_length=10)),
                ('mensaje_error', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complementos_pago', to=settings.AUTH_USER_MODEL)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complementos_pago', to='facturacion.factura')),
            ],
            options={
                'verbose_name_plural': 'complementos de pago',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
