# Generated by Django 6.0.7 on 2026-08-25 02:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tipo_movimiento', models.CharField(choices=[('ingreso', 'Ingreso'), ('retiro', 'Retiro')], max_length=10)),
                ('motivo', models.CharField(choices=[('venta', 'Venta'), ('gasto', 'Gasto'), ('ajuste', 'Ajuste'), ('retiro', 'Retiro')], max_length=20)),
                ('referencia_id', models.PositiveIntegerField(blank=True, null=True)),
                ('saldo_resultante', models.DecimalField(decimal_places=2, max_digits=12)),
                ('observacion', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_caja', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'movimientos de caja',
                'ordering': ['-fecha'],
            },
        ),
    ]
