# Generated by Django 6.0.7 on 2026-08-25 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientocaja',
            name='motivo',
            field=models.CharField(choices=[('venta', 'Venta'), ('ajuste', 'Ajuste'), ('manual', 'Manual')], max_length=20),
        ),
    ]
