# Generated by Django 6.0.7 on 2026-09-15 02:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0002_alter_movimientocaja_motivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientocaja',
            name='saldo_adicional_resultante',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='movimientocaja',
            name='motivo',
            field=models.CharField(choices=[('venta', 'Venta'), ('ajuste', 'Ajuste'), ('manual', 'Manual'), ('compra', 'Compra'), ('envio', 'Envío')], max_length=20),
        ),
    ]
