# Generated by Django 6.0.7 on 2026-08-26 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionPAC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.CharField(blank=True, max_length=100)),
                ('api_key_cifrada', models.TextField(blank=True)),
                ('api_endpoint', models.CharField(blank=True, max_length=255)),
                ('configuracion_extra', models.JSONField(blank=True, default=dict)),
                ('activo', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'configuración del PAC',
            },
        ),
        migrations.CreateModel(
            name='DatosFiscalesEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfc', models.CharField(blank=True, max_length=13, verbose_name='RFC')),
                ('razon_social', models.CharField(blank=True, max_length=255)),
                ('regimen_fiscal', models.CharField(blank=True, max_length=10)),
                ('codigo_postal_fiscal', models.CharField(blank=True, max_length=5)),
            ],
            options={
                'verbose_name_plural': 'datos fiscales de la empresa',
            },
        ),
        migrations.CreateModel(
            name='SerieFolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(max_length=10, unique=True)),
                ('folio_actual', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'series de folio',
                'ordering': ['serie'],
            },
        ),
    ]
