# Generated by Django 6.0.7 on 2026-08-25 01:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
        ('sucursales', '0002_historialestadosucursal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_item', models.CharField(choices=[('producto', 'Producto'), ('materia_prima', 'Materia prima')], max_length=20)),
                ('item_id', models.PositiveIntegerField()),
                ('tipo_movimiento', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], max_length=10)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('motivo', models.CharField(choices=[('compra', 'Compra'), ('venta', 'Venta'), ('produccion', 'Producción'), ('ajuste', 'Ajuste')], max_length=20)),
                ('referencia_id', models.PositiveIntegerField(blank=True, null=True)),
                ('stock_resultante', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_inventario', to='sucursales.sucursal')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_inventario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'movimientos de inventario',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['sucursal'], name='inventario__sucursa_d82659_idx'), models.Index(fields=['tipo_item', 'item_id'], name='inventario__tipo_it_7a1bbf_idx'), models.Index(fields=['fecha'], name='inventario__fecha_f978ae_idx')],
            },
        ),
    ]
