# Generated by Django 6.0.7 on 2026-08-25 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_movimientoinventario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoinventario',
            name='motivo',
            field=models.CharField(choices=[('compra', 'Compra'), ('venta', 'Venta'), ('produccion_consumo', 'Consumo de producción'), ('produccion_entrada', 'Entrada de producción'), ('ajuste', 'Ajuste')], max_length=20),
        ),
    ]
