# Generated by Django 6.0.7 on 2026-08-30 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsientoContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('concepto', models.CharField(max_length=255)),
                ('tipo_origen', models.CharField(choices=[('venta', 'Venta'), ('compra', 'Compra'), ('caja', 'Caja'), ('ajuste', 'Ajuste')], max_length=10)),
                ('referencia_id', models.PositiveIntegerField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asientos_contables', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'asientos contables',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='CuentaContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('activo', 'Activo'), ('pasivo', 'Pasivo'), ('capital', 'Capital'), ('ingreso', 'Ingreso'), ('egreso', 'Egreso')], max_length=10)),
                ('activo', models.BooleanField(default=True)),
                ('cuenta_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subcuentas', to='contabilidad.cuentacontable')),
            ],
            options={
                'verbose_name_plural': 'cuentas contables',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('cargo', 'Cargo'), ('abono', 'Abono')], max_length=5)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('asiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='contabilidad.asientocontable')),
                ('cuenta_contable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_contables', to='contabilidad.cuentacontable')),
            ],
            options={
                'verbose_name_plural': 'movimientos contables',
            },
        ),
    ]
