# Generated by Django 6.0.7 on 2026-08-25 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
        ('usuarios', '0002_codigorecuperacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='personas.empleado'),
        ),
    ]
