# Generated by Django 6.0.7 on 2026-09-23 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0001_initial'),
        ('usuarios', '0003_usuario_empleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='rrhh.empleado'),
        ),
    ]
