# Generated by Django 6.0.7 on 2026-09-23 23:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0002_rename_nombre_contactoemergencia_nombre_contacto_and_more'),
        ('usuarios', '0004_alter_usuario_empleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='empleado',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario', to='rrhh.empleado'),
        ),
        migrations.CreateModel(
            name='RegistroAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('exitoso', 'Inicio de sesión exitoso'), ('cierre_sesion', 'Cierre de sesión'), ('fallido', 'Intento fallido')], max_length=20)),
                ('email_intentado', models.CharField(blank=True, max_length=254)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registros_acceso', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
    ]
