# Generated by Django 6.0.7 on 2026-09-23 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
        ('usuarios', '0004_alter_usuario_empleado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Empleado',
        ),
    ]
