# Generated by Django 6.0.7 on 2026-09-23 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_alter_materiaprima_proveedor_principal'),
        ('compras', '0003_alter_compra_proveedor'),
        ('personas', '0002_delete_empleado'),
        ('ventas', '0004_alter_venta_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datosfiscalescliente',
            name='cliente',
        ),
        migrations.DeleteModel(
            name='Proveedor',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='DatosFiscalesCliente',
        ),
    ]
