# Generated by Django 6.0.7 on 2026-09-23 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactoemergencia',
            old_name='nombre',
            new_name='nombre_contacto',
        ),
        migrations.RenameField(
            model_name='dependiente',
            old_name='nombre',
            new_name='nombre_dependiente',
        ),
    ]
