# Generated by Django 6.0.7 on 2026-08-03 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=100)),
                ('descripcion_categoria', models.TextField(blank=True)),
                ('activo_categoria', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'categorías',
            },
        ),
        migrations.CreateModel(
            name='MateriaPrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_item', models.CharField(max_length=150)),
                ('unidad_medida', models.CharField(max_length=30)),
                ('costo_promedio', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('activo_item', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'materias primas',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=150)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('unidad_medida', models.CharField(max_length=30)),
                ('descripcion_producto', models.TextField(blank=True)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('costo_produccion', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('activo_producto', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='catalogo.categoria')),
            ],
        ),
    ]
