# Generated by Django 6.0.7 on 2026-08-25 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_renombrar_activo_y_agregar_tipo_categoria'),
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiaprima',
            name='proveedor_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materias_primas', to='personas.proveedor'),
        ),
    ]
