# Generated by Django 6.0.7 on 2026-09-23 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_materiaprima_proveedor_principal'),
        ('terceros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiaprima',
            name='proveedor_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materias_primas', to='terceros.proveedor'),
        ),
    ]
